using Microsoft.AspNetCore.Mvc;
using OnlineBookStore.Models;
using System.Diagnostics;

namespace OnlineBookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult GetTable(int? num)
        {
            ViewBag.num = num.HasValue ? num.Value : 0;
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        /* Model First approach
         * Create the model, Database will be automatically created
         * 
         * Database First Approach
         *  Database is already created, now model is autogenerated and changed are synced
         
         Entity Framework
            ORM: Object Relational Mapping framework
            Books Table - Create table .... SQL 
            Books table is a collection of rows
            each row is a book
        
            An ORM maps a row to a class
        
         SQL to MYsql, oracle
            your code will not change 
        
         Controller COde ---> Entity Framework ---> Provider ---> Database 
        Provider for SQL
        Provider for MySQL
        Provider for oracle 
        
         We will need to tell Entity framework
        about the table 
        
         
         Database (different)
            Settings:
            1) Username
            2) Password
            3) Database Server Location (how to access)
            4) Which database to connect
        
         If using Windows Authentication, Username and password is not needed*/
    }
}
